### ISSUE TITLE
Boostrap requirement

### ISSUE THREAD

**Issue by Android-James** [KirisakiXOnodera/Lab-Activity#20]
We currently don't have any framework for our HTML.

There are two ways we can proceed:

We can use Bootstrap to rewrite some parts of the webpage, such as the footer.
Alternatively, we can choose not to use any framework at all. (idk kase kung may html "framework" ba talaga. lmao para kasing wala)

**Comment by YouDontSayIt-dev** [comment]
Issue will now close due to activity completion
